pipeline {
    agent any
    /*agent {
        label {
            label ""
            customWorkspace "C:/work/${BRANCH_NAME}"
        }
    }*/

    environment {
        NEW_VERSION = '1.0.0'
    }

    stages {
        stage('Build') {
            steps {
                echo "workspace directory is ${workspace}"
                echo 'Building version ${NEW_VERSION}'
                sh './gradlew build'
            }
        }
        stage('Test') {
            steps {
                echo 'Testing version ${NEW_VERSION}'
                //sh './gradlew test'
            }
            /*post {
                always {
                    junit allowEmptyResults: false, testResults: "build/reports/tests/test/*.html"
                }
            }*/
        }
    }
}