pipeline {
    agent any

    environment {
        NEW_VERSION = '1.0.0'
    }

    stages {
        stage('Build') {
            steps {
                echo 'Building version ${NEW_VERSION}'
                gradle build
            }
        }
        stage('Test') {
            steps {
                echo 'Testing version ${NEW_VERSION}'
                sh './gradlew test'
            }
            /*post {
                always {
                    junit allowEmptyResults: false, testResults: "build/reports/tests/test/*.html"
                }
            }*/
        }
    }
}